<?xml version="1.0" encoding="utf-8"?>
<Database Name="RBV" Class="RBVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PERSONAL\SQLEXPRESS;Initial Catalog=RBV;Persist Security Info=True;User ID=USR_RBV;Context Connection=False" SettingsObjectName="RBV_AccesoDatos.Properties.Settings" SettingsPropertyName="RBVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_WebEvent_Events" Member="aspnet_WebEvent_Events">
    <Type Name="aspnet_WebEvent_Event">
      <Column Name="EventId" Type="System.String" DbType="Char(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventSequence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventOccurrence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDetailCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ApplicationPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ApplicationVirtualPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ExceptionType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tipoRecurso" Member="tipoRecurso">
    <Type Name="tipoRecurso">
      <Column Name="idTipoRecurso" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tipoRecurso" Member="tipoRecurso1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="tipoRecurso_recursosEmpresa" Member="recursosEmpresa" ThisKey="idTipoRecurso" OtherKey="idTipoRecurso" Type="recursosEmpresa" />
    </Type>
  </Table>
  <Table Name="dbo.segmentos" Member="segmentos">
    <Type Name="segmentos">
      <Column Name="idSegmento" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="segmentos_empresaSegmentos" Member="empresaSegmentos" ThisKey="idSegmento" OtherKey="idSegmento" Type="empresaSegmentos" />
    </Type>
  </Table>
  <Table Name="dbo.sectorEmpresa" Member="sectorEmpresa">
    <Type Name="sectorEmpresa">
      <Column Name="idSector" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="sector_sectorEmpresa" Member="sector" ThisKey="idSector" OtherKey="idSector" Type="sector" IsForeignKey="true" />
      <Association Name="empresa_sectorEmpresa" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sector" Member="sector">
    <Type Name="sector">
      <Column Name="idSector" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sector" Member="sector1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="sector_sectorEmpresa" Member="sectorEmpresa" ThisKey="idSector" OtherKey="idSector" Type="sectorEmpresa" />
    </Type>
  </Table>
  <Table Name="dbo.rolesInforme" Member="rolesInforme">
    <Type Name="rolesInforme">
      <Column Name="idRolInforme" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombreParticipante" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="rol" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idInforme" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="Informe_rolesInforme" Member="Informe" ThisKey="idInforme" OtherKey="idInforme" Type="Informe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.recursosEmpresa" Member="recursosEmpresa">
    <Type Name="recursosEmpresa">
      <Column Name="idRecursoEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="idTipoRecurso" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="recurso" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="recursosEmpresa_matrizValoracion" Member="matrizValoracion" ThisKey="idRecursoEmpresa" OtherKey="idRecursoEmpresa" Type="matrizValoracion" />
      <Association Name="tipoRecurso_recursosEmpresa" Member="tipoRecurso" ThisKey="idTipoRecurso" OtherKey="idTipoRecurso" Type="tipoRecurso" IsForeignKey="true" />
      <Association Name="empresa_recursosEmpresa" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.plantillaInforme" Member="plantillaInforme">
    <Type Name="plantillaInforme">
      <Column Name="idPlantillaInforme" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Introduccion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ElaboradoPor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="descripcionHeader" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="tituloPortada" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="nombreCarpetaInformesGenerados" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.matrizValoracion" Member="matrizValoracion">
    <Type Name="matrizValoracion">
      <Column Name="idRecursoEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idCaracteristicaRV" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="valor" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="recursosEmpresa_matrizValoracion" Member="recursosEmpresa" ThisKey="idRecursoEmpresa" OtherKey="idRecursoEmpresa" Type="recursosEmpresa" IsForeignKey="true" />
      <Association Name="caracteristicaRecursoValioso_matrizValoracion" Member="caracteristicaRecursoValioso" ThisKey="idCaracteristicaRV" OtherKey="idCaracteristicaRV" Type="caracteristicaRecursoValioso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.lineaDeNegocio" Member="lineaDeNegocio">
    <Type Name="lineaDeNegocio">
      <Column Name="idLineaNegocio" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lineaNegocio" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="empresa_lineaDeNegocio" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Informe" Member="Informe">
    <Type Name="Informe">
      <Column Name="idInforme" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="fechaGeneracion" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="rutaArchivo" Type="System.String" DbType="VarChar(220) NOT NULL" CanBeNull="false" />
      <Association Name="Informe_rolesInforme" Member="rolesInforme" ThisKey="idInforme" OtherKey="idInforme" Type="rolesInforme" />
      <Association Name="empresa_Informe" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.escalaValoracion" Member="escalaValoracion">
    <Type Name="escalaValoracion">
      <Column Name="idCaracteristicaRV" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="empresa_escalaValoracion" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
      <Association Name="caracteristicaRecursoValioso_escalaValoracion" Member="caracteristicaRecursoValioso" ThisKey="idCaracteristicaRV" OtherKey="idCaracteristicaRV" Type="caracteristicaRecursoValioso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.escalaCalificacion" Member="escalaCalificacion">
    <Type Name="escalaCalificacion">
      <Column Name="IdEscalaCalificacion" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Escala" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="empresa_escalaCalificacion" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.empresaUsuario" Member="empresaUsuario">
    <Type Name="empresaUsuario">
      <Column Name="idUsuarioEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="empresa_empresaUsuario" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
      <Association Name="aspnet_Membership_empresaUsuario" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.empresaSegmentos" Member="empresaSegmentos">
    <Type Name="empresaSegmentos">
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idSegmento" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="segmentos_empresaSegmentos" Member="segmentos" ThisKey="idSegmento" OtherKey="idSegmento" Type="segmentos" IsForeignKey="true" />
      <Association Name="empresa_empresaSegmentos" Member="empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.empresa" Member="empresa">
    <Type Name="empresa">
      <Column Name="idEmpresa" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nombreEmpresa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="represetanteLegal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="empresa_sectorEmpresa" Member="sectorEmpresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="sectorEmpresa" />
      <Association Name="empresa_recursosEmpresa" Member="recursosEmpresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="recursosEmpresa" />
      <Association Name="empresa_lineaDeNegocio" Member="lineaDeNegocio" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="lineaDeNegocio" />
      <Association Name="empresa_Informe" Member="Informe" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="Informe" />
      <Association Name="empresa_escalaValoracion" Member="escalaValoracion" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="escalaValoracion" />
      <Association Name="empresa_escalaCalificacion" Member="escalaCalificacion" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="escalaCalificacion" />
      <Association Name="empresa_empresaUsuario" Member="empresaUsuario" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresaUsuario" />
      <Association Name="empresa_empresaSegmentos" Member="empresaSegmentos" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="empresaSegmentos" />
    </Type>
  </Table>
  <Table Name="dbo.ELMAH_Error" Member="ELMAH_Error">
    <Type Name="ELMAH_Error">
      <Column Name="ErrorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Application" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Host" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="[User]" Member="User" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AllXml" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.codigoCIIU" Member="codigoCIIU">
    <Type Name="codigoCIIU">
      <Column Name="idCodigoCIIU" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigoCIIU" Member="codigoCIIU1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.clasificacionRecursoValioso" Member="clasificacionRecursoValioso">
    <Type Name="clasificacionRecursoValioso">
      <Column Name="idClasificacionRV" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clasificacionRV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="clasificacionRecursoValioso_caracteristicaRecursoValioso" Member="caracteristicaRecursoValioso" ThisKey="idClasificacionRV" OtherKey="idClasificacionRV" Type="caracteristicaRecursoValioso" />
    </Type>
  </Table>
  <Table Name="dbo.caracteristicaRecursoValioso" Member="caracteristicaRecursoValioso">
    <Type Name="caracteristicaRecursoValioso">
      <Column Name="idCaracteristicaRV" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="caracteristicaRV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idClasificacionRV" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="caracteristicaRecursoValioso_matrizValoracion" Member="matrizValoracion" ThisKey="idCaracteristicaRV" OtherKey="idCaracteristicaRV" Type="matrizValoracion" />
      <Association Name="caracteristicaRecursoValioso_escalaValoracion" Member="escalaValoracion" ThisKey="idCaracteristicaRV" OtherKey="idCaracteristicaRV" Type="escalaValoracion" />
      <Association Name="clasificacionRecursoValioso_caracteristicaRecursoValioso" Member="clasificacionRecursoValioso" ThisKey="idClasificacionRV" OtherKey="idClasificacionRV" Type="clasificacionRecursoValioso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_WebEvent_Events" Member="aspnet_WebEvent_Events1">
    <Type Name="aspnet_WebEvent_Events">
      <Column Name="EventId" Type="System.String" DbType="Char(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventSequence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventOccurrence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDetailCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ApplicationPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ApplicationVirtualPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ExceptionType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRoles">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_UsersInRoles" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
      <Association Name="aspnet_Roles_aspnet_UsersInRoles" Member="aspnet_Roles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_Users">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_UsersInRoles" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRoles" />
      <Association Name="aspnet_Users_aspnet_Profile" Member="aspnet_Profile" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Profile" Cardinality="One" />
      <Association Name="aspnet_Users_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUser" ThisKey="UserId" OtherKey="UserId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_SchemaVersions" Member="aspnet_SchemaVersions">
    <Type Name="aspnet_SchemaVersions">
      <Column Name="Feature" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompatibleSchemaVersion" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsCurrentVersion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Roles">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Roles_aspnet_UsersInRoles" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRoles" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="aspnet_Profile">
    <Type Name="aspnet_Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_Profile" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUser">
    <Type Name="aspnet_PersonalizationPerUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_PersonalizationPerUser" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationPerUser" Member="aspnet_Paths" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Paths" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers">
    <Type Name="aspnet_PersonalizationAllUsers">
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationAllUsers" Member="aspnet_Paths" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Paths" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Paths" Member="aspnet_Paths">
    <Type Name="aspnet_Paths">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUser" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Paths_aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationAllUsers" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Membership">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdEmpresa" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="aspnet_Membership_empresaUsuario" Member="empresaUsuario" ThisKey="UserId" OtherKey="UserId" Type="empresaUsuario" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.aspnet_Membership_GetPassword" Method="aspnet_Membership_GetPassword">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="MaxInvalidPasswordAttempts" Parameter="maxInvalidPasswordAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAttemptWindow" Parameter="passwordAttemptWindow" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PasswordAnswer" Parameter="passwordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <ElementType Name="aspnet_Membership_GetPasswordResult">
      <Column Name="Column1" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Column2" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_AnyDataInTables" Method="aspnet_AnyDataInTables">
    <Parameter Name="TablesToCheck" Parameter="tablesToCheck" Type="System.Int32" DbType="Int" />
    <ElementType Name="aspnet_AnyDataInTablesResult">
      <Column Name="Column1" Type="System.String" DbType="NVarChar(17) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Applications_CreateApplication" Method="aspnet_Applications_CreateApplication">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_CheckSchemaVersion" Method="aspnet_CheckSchemaVersion">
    <Parameter Name="Feature" Parameter="feature" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="CompatibleSchemaVersion" Parameter="compatibleSchemaVersion" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_ChangePasswordQuestionAndAnswer" Method="aspnet_Membership_ChangePasswordQuestionAndAnswer">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPasswordQuestion" Parameter="newPasswordQuestion" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPasswordAnswer" Parameter="newPasswordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_FindUsersByEmail" Method="aspnet_Membership_FindUsersByEmail">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="EmailToMatch" Parameter="emailToMatch" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_CreateUser" Method="aspnet_Membership_CreateUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="PasswordSalt" Parameter="passwordSalt" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PasswordQuestion" Parameter="passwordQuestion" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PasswordAnswer" Parameter="passwordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="IsApproved" Parameter="isApproved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CreateDate" Parameter="createDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UniqueEmail" Parameter="uniqueEmail" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordFormat" Parameter="passwordFormat" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_FindUsersByName" Method="aspnet_Membership_FindUsersByName">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserNameToMatch" Parameter="userNameToMatch" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_GetAllUsers" Method="aspnet_Membership_GetAllUsers">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_GetNumberOfUsersOnline" Method="aspnet_Membership_GetNumberOfUsersOnline">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="MinutesSinceLastInActive" Parameter="minutesSinceLastInActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_GetPasswordWithFormat" Method="aspnet_Membership_GetPasswordWithFormat">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UpdateLastLoginActivityDate" Parameter="updateLastLoginActivityDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="aspnet_Membership_GetPasswordWithFormatResult">
      <Column Name="Column1" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Column2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Column3" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Column4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Column5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Column6" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Column7" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Column8" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Membership_GetUserByEmail" Method="aspnet_Membership_GetUserByEmail">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_Membership_GetUserByEmailResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Membership_GetUserByName" Method="aspnet_Membership_GetUserByName">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UpdateLastActivity" Parameter="updateLastActivity" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="aspnet_Membership_GetUserByNameResult">
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Membership_GetUserByUserId" Method="aspnet_Membership_GetUserByUserId">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UpdateLastActivity" Parameter="updateLastActivity" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="aspnet_Membership_GetUserByUserIdResult">
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Membership_ResetPassword" Method="aspnet_Membership_ResetPassword">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPassword" Parameter="newPassword" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="MaxInvalidPasswordAttempts" Parameter="maxInvalidPasswordAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAttemptWindow" Parameter="passwordAttemptWindow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordSalt" Parameter="passwordSalt" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PasswordFormat" Parameter="passwordFormat" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAnswer" Parameter="passwordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_SetPassword" Method="aspnet_Membership_SetPassword">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPassword" Parameter="newPassword" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="PasswordSalt" Parameter="passwordSalt" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PasswordFormat" Parameter="passwordFormat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_UnlockUser" Method="aspnet_Membership_UnlockUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_UpdateUser" Method="aspnet_Membership_UpdateUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="NText" />
    <Parameter Name="IsApproved" Parameter="isApproved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LastLoginDate" Parameter="lastLoginDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastActivityDate" Parameter="lastActivityDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UniqueEmail" Parameter="uniqueEmail" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_UpdateUserInfo" Method="aspnet_Membership_UpdateUserInfo">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="IsPasswordCorrect" Parameter="isPasswordCorrect" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdateLastLoginActivityDate" Parameter="updateLastLoginActivityDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MaxInvalidPasswordAttempts" Parameter="maxInvalidPasswordAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAttemptWindow" Parameter="passwordAttemptWindow" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastLoginDate" Parameter="lastLoginDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastActivityDate" Parameter="lastActivityDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Paths_CreatePath" Method="aspnet_Paths_CreatePath">
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PathId" Parameter="pathId" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Personalization_GetApplicationId" Method="aspnet_Personalization_GetApplicationId">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAdministration_DeleteAllState" Method="aspnet_PersonalizationAdministration_DeleteAllState">
    <Parameter Name="AllUsersScope" Parameter="allUsersScope" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAdministration_FindState" Method="aspnet_PersonalizationAdministration_FindState">
    <Parameter Name="AllUsersScope" Parameter="allUsersScope" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="InactiveSinceDate" Parameter="inactiveSinceDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAdministration_GetCountOfState" Method="aspnet_PersonalizationAdministration_GetCountOfState">
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="AllUsersScope" Parameter="allUsersScope" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="InactiveSinceDate" Parameter="inactiveSinceDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAdministration_ResetSharedState" Method="aspnet_PersonalizationAdministration_ResetSharedState">
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAdministration_ResetUserState" Method="aspnet_PersonalizationAdministration_ResetUserState">
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="InactiveSinceDate" Parameter="inactiveSinceDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAllUsers_GetPageSettings" Method="aspnet_PersonalizationAllUsers_GetPageSettings">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_PersonalizationAllUsers_GetPageSettingsResult">
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAllUsers_ResetPageSettings" Method="aspnet_PersonalizationAllUsers_ResetPageSettings">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationAllUsers_SetPageSettings" Method="aspnet_PersonalizationAllUsers_SetPageSettings">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PageSettings" Parameter="pageSettings" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_PersonalizationPerUser_GetPageSettings" Method="aspnet_PersonalizationPerUser_GetPageSettings">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="aspnet_PersonalizationPerUser_GetPageSettingsResult">
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Profile_DeleteInactiveProfiles" Method="aspnet_Profile_DeleteInactiveProfiles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ProfileAuthOptions" Parameter="profileAuthOptions" Type="System.Int32" DbType="Int" />
    <Parameter Name="InactiveSinceDate" Parameter="inactiveSinceDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="aspnet_Profile_DeleteInactiveProfilesResult">
      <Column Name="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Profile_DeleteProfiles" Method="aspnet_Profile_DeleteProfiles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserNames" Parameter="userNames" Type="System.String" DbType="NVarChar(4000)" />
    <ElementType Name="aspnet_Profile_DeleteProfilesResult">
      <Column Name="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Profile_GetProfiles" Method="aspnet_Profile_GetProfiles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ProfileAuthOptions" Parameter="profileAuthOptions" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserNameToMatch" Parameter="userNameToMatch" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="InactiveSinceDate" Parameter="inactiveSinceDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Profile_GetNumberOfInactiveProfiles" Method="aspnet_Profile_GetNumberOfInactiveProfiles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ProfileAuthOptions" Parameter="profileAuthOptions" Type="System.Int32" DbType="Int" />
    <Parameter Name="InactiveSinceDate" Parameter="inactiveSinceDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="aspnet_Profile_GetNumberOfInactiveProfilesResult">
      <Column Name="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Profile_GetProperties" Method="aspnet_Profile_GetProperties">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="aspnet_Profile_GetPropertiesResult">
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Profile_SetProperties" Method="aspnet_Profile_SetProperties">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PropertyNames" Parameter="propertyNames" Type="System.String" DbType="NText" />
    <Parameter Name="PropertyValuesString" Parameter="propertyValuesString" Type="System.String" DbType="NText" />
    <Parameter Name="PropertyValuesBinary" Parameter="propertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="IsUserAnonymous" Parameter="isUserAnonymous" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_RegisterSchemaVersion" Method="aspnet_RegisterSchemaVersion">
    <Parameter Name="Feature" Parameter="feature" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="CompatibleSchemaVersion" Parameter="compatibleSchemaVersion" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="IsCurrentVersion" Parameter="isCurrentVersion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="RemoveIncompatibleSchema" Parameter="removeIncompatibleSchema" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Roles_CreateRole" Method="aspnet_Roles_CreateRole">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Roles_DeleteRole" Method="aspnet_Roles_DeleteRole">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="DeleteOnlyIfRoleIsEmpty" Parameter="deleteOnlyIfRoleIsEmpty" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Roles_GetAllRoles" Method="aspnet_Roles_GetAllRoles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_Roles_GetAllRolesResult">
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Roles_RoleExists" Method="aspnet_Roles_RoleExists">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Setup_RemoveAllRoleMembers" Method="aspnet_Setup_RemoveAllRoleMembers">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Setup_RestorePermissions" Method="aspnet_Setup_RestorePermissions">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_UnRegisterSchemaVersion" Method="aspnet_UnRegisterSchemaVersion">
    <Parameter Name="Feature" Parameter="feature" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="CompatibleSchemaVersion" Parameter="compatibleSchemaVersion" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Users_CreateUser" Method="aspnet_Users_CreateUser">
    <Parameter Name="ApplicationId" Parameter="applicationId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="IsUserAnonymous" Parameter="isUserAnonymous" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LastActivityDate" Parameter="lastActivityDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Users_DeleteUser" Method="aspnet_Users_DeleteUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="TablesToDeleteFrom" Parameter="tablesToDeleteFrom" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumTablesDeletedFrom" Parameter="numTablesDeletedFrom" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_UsersInRoles_AddUsersToRoles" Method="aspnet_UsersInRoles_AddUsersToRoles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserNames" Parameter="userNames" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="RoleNames" Parameter="roleNames" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="aspnet_UsersInRoles_AddUsersToRolesResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_UsersInRoles_FindUsersInRole" Method="aspnet_UsersInRoles_FindUsersInRole">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserNameToMatch" Parameter="userNameToMatch" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_UsersInRoles_FindUsersInRoleResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_UsersInRoles_GetRolesForUser" Method="aspnet_UsersInRoles_GetRolesForUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_UsersInRoles_GetRolesForUserResult">
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_UsersInRoles_GetUsersInRoles" Method="aspnet_UsersInRoles_GetUsersInRoles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_UsersInRoles_GetUsersInRolesResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_UsersInRoles_IsUserInRole" Method="aspnet_UsersInRoles_IsUserInRole">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_UsersInRoles_RemoveUsersFromRoles" Method="aspnet_UsersInRoles_RemoveUsersFromRoles">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserNames" Parameter="userNames" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="RoleNames" Parameter="roleNames" Type="System.String" DbType="NVarChar(4000)" />
    <ElementType Name="aspnet_UsersInRoles_RemoveUsersFromRolesResult">
      <Column Name="Column1" Type="System.Char" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_WebEvent_LogEvent" Method="aspnet_WebEvent_LogEvent">
    <Parameter Name="EventId" Parameter="eventId" Type="System.String" DbType="Char(32)" />
    <Parameter Name="EventTimeUtc" Parameter="eventTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EventTime" Parameter="eventTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EventType" Parameter="eventType" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="EventSequence" Parameter="eventSequence" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="EventOccurrence" Parameter="eventOccurrence" Type="System.Decimal" DbType="Decimal" />
    <Parameter Name="EventCode" Parameter="eventCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="EventDetailCode" Parameter="eventDetailCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="NVarChar(1024)" />
    <Parameter Name="ApplicationPath" Parameter="applicationPath" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="ApplicationVirtualPath" Parameter="applicationVirtualPath" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="MachineName" Parameter="machineName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RequestUrl" Parameter="requestUrl" Type="System.String" DbType="NVarChar(1024)" />
    <Parameter Name="ExceptionType" Parameter="exceptionType" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Details" Parameter="details" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
</Database>