//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Clase Error.
/// </summary>
/// <remarks>
/// Clase generada automáticamente.
/// </remarks>
public partial class Error {
    
    /// <summary>
    /// Control ltrError.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal ltrError;
    
    /// <summary>
    /// Control ltrmsgError.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal ltrmsgError;
}
